name: flutter_grocery
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  provider: ^6.1.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  photo_view: ^0.15.0
  dio: ^5.4.3+1
  image_picker: ^1.1.0
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.12.1
  flutter_google_places: ^0.3.0
  geocoding: ^3.0.0
  geolocator: ^14.0.0
  shimmer_animation: ^2.2.2
  url_launcher: ^6.1.11
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.3
  connectivity_plus: ^5.0.2
  carousel_slider: ^5.0.0
  fluro: ^2.0.5
  universal_html: ^2.2.4
  flutter_widget_from_html_core: ^0.16.0
  country_code_picker: ^3.0.0
  flutter_typeahead: ^5.2.0
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.4.1
  audioplayers: ^6.0.0
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^6.3.0
  dotted_border: ^2.1.0
  share_plus: ^11.0.0
  scroll_to_index: ^3.0.1
  simple_speed_dial: ^0.1.7
  sign_in_with_apple: ^7.0.1
  firebase_auth: ^5.5.3
  flutter_svg: ^2.1.0
  flutter_xlider: ^3.5.0
  firebase_crashlytics: ^4.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
