name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: '34.0.0'
          platform-version: '34'

      - name: Clone Flutter 3.22.1
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.22.1 --depth 1 flutter_sdk
          echo "$GITHUB_WORKSPACE/flutter_sdk/bin" >> $GITHUB_PATH

      - name: Run flutter doctor
        run: flutter doctor

      - name: Precache required tools
        run: flutter precache

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
