name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: '34.0.0'
          platform-version: '34'

      # ✅ Manually download Flutter 3.22.1 to ensure Dart >= 3.5.0
      - name: Install Flutter 3.22.1
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.22.1 --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      # ✅ Confirm Flutter & Dart versions
      - name: Check Flutter & Dart version
        run: flutter --version

      # Install dependencies & build
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --release

      # Upload APK
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
