name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Setup Java 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Setup Android SDK
      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: '34.0.0'
          platform-version: '34'

      # 3. Setup Flutter with exact version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # Includes Dart 3.4.0
          channel: 'stable'

      # 4. Clean and reset
      - run: flutter clean
      - run: dart pub cache repair

      # 5. Get dependencies
      - run: flutter pub get

      # 6. Build
      - run: flutter build apk --release

      # 7. Upload APK
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
