name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Setup Java 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Setup Android SDK
      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: '34.0.0'
          platform-version: '34'
          ndk-version: '25.2.9519653'

      # 3. Setup Flutter with exact version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # Includes Dart 3.4.0
          channel: 'stable'

      # 4. Accept Android licenses
      - run: yes | sdkmanager --licenses
      - run: flutter doctor --android-licenses

      # 5. Dependency resolution and build
      - run: |
          flutter pub cache repair
          flutter clean
          flutter pub get --no-offline
          flutter build apk --release

      # 6. Upload APK
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
