name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Java 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Android SDK with required version
      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: '35.0.0'
          platform-version: '35'

      # 3. Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # 4. Accept licenses
      - run: yes | sdkmanager --licenses
      - run: flutter doctor --android-licenses

      # 5. Build
      - run: flutter pub get
      - run: flutter build apk --release

      # 6. Upload APK
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
