name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ✅ Use Java 17 (required by Android SDK)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'  # Changed from 11 to 17

      # ✅ Use the OFFICIAL Android setup (google-github-actions)
      - uses: google-github-actions/setup-android@v1

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
