name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Install Java 17 (MUST for Android SDK)
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. PROPER Android setup (official action)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 3. Flutter setup
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'  # Explicit version
          channel: 'stable'

      # 4. Build steps
      - run: flutter pub get
      - run: flutter build apk --release

      # 5
