name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_HOME: ${{ github.workspace }}/flutter
      PUB_CACHE: ${{ github.workspace }}/.pub-cache

    steps:
      - uses: actions/checkout@v4

      # 1. Setup Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Setup Android SDK
      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: '34.0.0'
          platform-version: '34'
          ndk-version: '25.2.9519653'

      # 3. Install Flutter 3.22.1
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.22.1 --depth 1 $FLUTTER_HOME
          echo "$FLUTTER_HOME/bin" >> $GITHUB_PATH
          echo "::add-path::$FLUTTER_HOME/bin"

      # 4. Verify installation
      - name: Check Flutter version
        run: |
          flutter --version
          dart --version

      # 5. Setup environment
      - name: Setup environment
        run: |
          flutter precache
          flutter doctor -v

      # 6. Get dependencies
      - name: Get packages
        run: flutter pub get

      # 7. Build APK
      - name: Build release APK
        run: |
          flutter clean
          flutter build apk --release

      # 8. Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
