name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Clone Flutter 3.22.1 SDK
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.22.1 --depth 1 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Check Flutter version (MUST show 3.22.1 / Dart 3.5.0)
        run: flutter --version

      - name: Precache dependencies
        run: flutter precache

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
