name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Setup Java 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. Setup Android SDK
      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: '35.0.0'
          platform-version: '35'

      # 3. Setup Flutter (using stable channel)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      # 4. Accept licenses
      - run: yes | sdkmanager --licenses
      - run: flutter doctor --android-licenses

      # 5. Get dependencies (without major upgrades)
      - run: flutter pub get

      # 6. Apply country_code_picker fix
      - name: Patch SelectionDialog
        run: |
          sed -i "s/SelectionDialog(/SelectionDialog(hideHeaderText: false, headerAlignment: Alignment.center, /g" lib/features/auth/widgets/country_code_picker_widget.dart
          sed -i "s/elements,/elements: elements,/g" lib/features/auth/widgets/country_code_picker_widget.dart
          sed -i "s/favoriteElements,/favoriteElements: favoriteElements,/g" lib/features/auth/widgets/country_code_picker_widget.dart

      # 7. Build
      - run: flutter clean
      - run: flutter build apk --release

      # 8. Upload APK
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
